# Documentation available at https://expeditor.chef.io/docs/getting-started/

# The name of the product keys for this product (from mixlib-install)
product_key:
  - chef-workstation

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: chef-ws-notify

docker_images:
  - chefworkstation

github:
  # This deletes the GitHub PR branch after successfully merged into the release branch
  delete_branch_on_merge: true
  # allow bumping the minor release via label
  minor_bump_labels:
    - "Expeditor: Bump Version Minor"
  # allow bumping the major release via label
  major_bump_labels:
    - "Expeditor: Bump Version Major"
# https://expeditor.chef.io/docs/getting-started/subscriptions/#merge-actions
# The `merge_actions` key is a shortcut for the
# `pull_request_merged:<GITHUB_REPO>:<RELEASE_BRANCH>:*` subscription.
merge_actions:
  - built_in:bump_version:
      ignore_labels:
        - "Expeditor: Skip Version Bump"
        - "Expeditor: Skip All"
  - built_in:update_changelog:
      ignore_labels:
        - "Expeditor: Skip Changelog"
        - "Expeditor: Skip All"
  - trigger_pipeline:omnibus/release:
      ignore_labels:
        - "Expeditor: Skip Omnibus"
        - "Expeditor: Skip All"
      only_if: built_in:bump_version

pipelines:
  - verify:
      description: Pull Request validation tests
  - omnibus/release
  - omnibus/adhoc:
      definition: .expeditor/release.omnibus.yml
      env:
        - ADHOC: true

subscriptions:
  - workload: artifact_published:unstable:chef-workstation:{{version_constraint}}
    actions:
      - built_in:build_docker_image
  - workload: artifact_published:current:chef-workstation:{{version_constraint}}
    actions:
      - built_in:tag_docker_image
  - workload: artifact_published:stable:chef-workstation:{{version_constraint}}
    actions:
      - built_in:rollover_changelog
      - bash:.expeditor/update_dockerfile.sh
      - bash:.expeditor/publish-release-notes.sh
      - bash:.expeditor/purge-cdn.sh
      - bash:.expeditor/announce-release.sh
      - built_in:tag_docker_image
  - workload: chef/chef-workstation-app:master_completed:pull_request_merged:chef/chef-workstation-app:master:*
    actions:
      - bash:.expeditor/update_chef-workstation-app_to_latest.sh
  - workload: chef/delivery-cli:master_completed:pull_request_merged:chef/delivery-cli:master:*
    actions:
      - bash:.expeditor/update_delivery-cli_to_latest.sh
  - workload: artifact_published:stable:chef:15*
    actions:
      # update our pinned version for chef/chef-bin in Gemfile
      - bash:.expeditor/update_chef.sh
      # update gemfile.lock and make it a PR
      - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:appbundler-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:berkshelf-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:chef-cli-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:chef-apply-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:chef-sugar-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:chef-telemetry-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:chef-vault-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:chef-zero-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:cheffish-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:chefspec-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:chefstyle-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:cookbook-omnifetch-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:cookstyle-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:fauxhai-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:ffi-yajl-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:foodcritic-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:inspec-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:kitchen-azurerm-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:kitchen-digitalocean-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:kitchen-dokken-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:kitchen-ec2-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:kitchen-google-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:kitchen-hyperv-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:kitchen-inspec-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:kitchen-vagrant-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:kitchen-vcenter-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:knife-acl-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:knife-cloud-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:knife-ec2-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:knife-google-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:knife-opc-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:knife-push-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:knife-tidy-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:knife-vsphere-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:knife-vsphere-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:knife-windows-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:libyajl2-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:license-acceptance-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:mixlib-archive-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:mixlib-authentication-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:mixlib-cli-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:mixlib-config-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:mixlib-install-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:mixlib-log-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:mixlib-shellout-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:mixlib-versioning-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:nokogiri-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:ohai-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:opscode-pushy-client-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:stove-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:test-kitchen-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:train-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:win32-event-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:win32-eventlog-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:win32-ipc-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:win32-mmap-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:win32-mutex-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:win32-process-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:win32-service-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:win32-taskscheduler-*
    actions:
       - bash:.expeditor/update_dep.sh
  - workload: ruby_gem_published:wmi-lite
